// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: image_service.proto

package image_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *ImageRequest) Reset() {
	*x = ImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRequest) ProtoMessage() {}

func (x *ImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRequest.ProtoReflect.Descriptor instead.
func (*ImageRequest) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{0}
}

func (x *ImageRequest) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type ProgressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*ProgressResponse_Progress
	//	*ProgressResponse_ProcessedImage
	Data isProgressResponse_Data `protobuf_oneof:"data"`
}

func (x *ProgressResponse) Reset() {
	*x = ProgressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_image_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressResponse) ProtoMessage() {}

func (x *ProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressResponse.ProtoReflect.Descriptor instead.
func (*ProgressResponse) Descriptor() ([]byte, []int) {
	return file_image_service_proto_rawDescGZIP(), []int{1}
}

func (m *ProgressResponse) GetData() isProgressResponse_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *ProgressResponse) GetProgress() int32 {
	if x, ok := x.GetData().(*ProgressResponse_Progress); ok {
		return x.Progress
	}
	return 0
}

func (x *ProgressResponse) GetProcessedImage() []byte {
	if x, ok := x.GetData().(*ProgressResponse_ProcessedImage); ok {
		return x.ProcessedImage
	}
	return nil
}

type isProgressResponse_Data interface {
	isProgressResponse_Data()
}

type ProgressResponse_Progress struct {
	Progress int32 `protobuf:"varint,1,opt,name=progress,proto3,oneof"`
}

type ProgressResponse_ProcessedImage struct {
	ProcessedImage []byte `protobuf:"bytes,2,opt,name=processedImage,proto3,oneof"`
}

func (*ProgressResponse_Progress) isProgressResponse_Data() {}

func (*ProgressResponse_ProcessedImage) isProgressResponse_Data() {}

var File_image_service_proto protoreflect.FileDescriptor

var file_image_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x0c, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x62, 0x0a, 0x10, 0x50,
	0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1c, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x48, 0x00, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x28, 0x0a,
	0x0e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x65, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32,
	0x4c, 0x0a, 0x15, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x47, 0x72, 0x61, 0x79, 0x73, 0x63, 0x61, 0x6c,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x0b, 0x55, 0x70, 0x6c, 0x6f,
	0x61, 0x64, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x0d, 0x2e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_image_service_proto_rawDescOnce sync.Once
	file_image_service_proto_rawDescData = file_image_service_proto_rawDesc
)

func file_image_service_proto_rawDescGZIP() []byte {
	file_image_service_proto_rawDescOnce.Do(func() {
		file_image_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_image_service_proto_rawDescData)
	})
	return file_image_service_proto_rawDescData
}

var file_image_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_image_service_proto_goTypes = []interface{}{
	(*ImageRequest)(nil),     // 0: ImageRequest
	(*ProgressResponse)(nil), // 1: ProgressResponse
}
var file_image_service_proto_depIdxs = []int32{
	0, // 0: ImageGrayscaleService.UploadImage:input_type -> ImageRequest
	1, // 1: ImageGrayscaleService.UploadImage:output_type -> ProgressResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_image_service_proto_init() }
func file_image_service_proto_init() {
	if File_image_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_image_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_image_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProgressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_image_service_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ProgressResponse_Progress)(nil),
		(*ProgressResponse_ProcessedImage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_image_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_image_service_proto_goTypes,
		DependencyIndexes: file_image_service_proto_depIdxs,
		MessageInfos:      file_image_service_proto_msgTypes,
	}.Build()
	File_image_service_proto = out.File
	file_image_service_proto_rawDesc = nil
	file_image_service_proto_goTypes = nil
	file_image_service_proto_depIdxs = nil
}
