# Pod definition
kind: Pod 
apiVersion: v1
metadata:
  name: frontend-app
  labels:
    app: frontend
spec:
  containers:
    - name: frontend
      image: thijsheijden/microservice-example:latest
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName